name: Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'
      - 'dev'
      - 'feature/*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ "ubuntu-22.04", "ubuntu-24.04", "macos-latest", "windows-latest" ]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.26"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd)/jaddek_tillo_sdk" >> $GITHUB_ENV


      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run Ruff
        run: uv run ruff check

      - name: Run Pytests
        run: uv run pytest tests/

      - name: Upload artifact
        if: ${{ success() && matrix.python-version == '3.11' && matrix.os == 'ubuntu-22.04' }}
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ./


#  set-release-tag:
#    runs-on: ubuntu-latest
#    needs: ["build"]
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: artifact
#          path: ./
#      - name: Bump version
#        run: |
#          ls -la
#          pip install bump-my-version
#          bump-my-version bump patch --dry-run -vv --allow-dirty
